USE Blog;

CREATE TABLE dbo.PostLog
(
  PostLogId INT NOT NULL IDENTITY,
  [Date] DATETIME NOT NULL DEFAULT(SYSDATETIME()),
  LoginName sysname NOT NULL DEFAULT(ORIGINAL_LOGIN()),
  [Action] CHAR(1) NOT NULL,
  PostId INT NOT NULL,
  PostTitle NVARCHAR(MAX) NOT NULL,
  CONSTRAINT PK_PostLogId
    PRIMARY KEY(PostLogId)
);